name: Demo Workflow
on:
  push:
    branches:
      - dev
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Demo Step
        run: echo "This is a dev demo step"
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Demo Step 2
        run: echo "This is Demo 2"
