name: Demo Workflow
on:
  push:
    branches:
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest    
    outputs:
      message: ${{ steps.test-output.outputs.message }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Set Output
        id: test-output
        run: echo "message=success" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Get Message from Lint
        run: echo "${{ needs.lint.outputs.message }}"

